USE [database1]
GO

/****** Object:  Table [dbo].[USERS]    Script Date: 7/9/2021 2:34:27 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USERS](
	[USER_ID] [nvarchar](50) NOT NULL,
	[NICK_NAME] [nvarchar](50) NOT NULL,
	[PWD_HASH] [nvarchar](50) NOT NULL,
	[DATE_CREATED] [date] NOT NULL,
	[PERMISSIONS] [nvarchar](50) NULL,
	[IS_DELETED] [nvarchar](1) NULL,
PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO



USE [database1]
GO

/****** Object:  Table [dbo].[MESSAGES]    Script Date: 7/9/2021 2:30:22 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MESSAGES](
	[MESSAGE_ID] [nvarchar](50) NOT NULL,
	[SENDER_USER_ID] [nvarchar](50) NOT NULL,
	[RECEIVER_USER_ID] [nvarchar](50) NOT NULL,
	[DATE_TIME_SENT] [datetime] NOT NULL,
	[DATE_TIME_RECEIVED] [datetime] NULL,
	[MESSAGE_TEXT] [nvarchar](1000) NULL,
	[MESSAGE_OBJECT] [image] NULL,
	[RECEIVER_RECEIVED_FL] [nchar](1) NULL,
PRIMARY KEY CLUSTERED 
(
	[MESSAGE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[MESSAGES]  WITH CHECK ADD  CONSTRAINT [FK_MESSAGES_RECEIVER_ID] FOREIGN KEY([RECEIVER_USER_ID])
REFERENCES [dbo].[USERS] ([USER_ID])
GO

ALTER TABLE [dbo].[MESSAGES] CHECK CONSTRAINT [FK_MESSAGES_RECEIVER_ID]
GO

ALTER TABLE [dbo].[MESSAGES]  WITH CHECK ADD  CONSTRAINT [FK_MESSAGES_SENDER_ID] FOREIGN KEY([SENDER_USER_ID])
REFERENCES [dbo].[USERS] ([USER_ID])
GO

ALTER TABLE [dbo].[MESSAGES] CHECK CONSTRAINT [FK_MESSAGES_SENDER_ID]
GO


insert into [dbo].[USERS]
values('2','mihai2','-1063954649','2021-05-12','user',NULL);
commit;